import {mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {resolve,join} from 'node:path';
import {normalizeAccount} from '../src/account.mjs';
import {OPERATIONS} from '../src/approvals.mjs';
const args=process.argv.slice(2),root=resolve(import.meta.dirname,'..');
if(args.length<2||args[0]!=='--account-email'||args.some((v,i)=>i>1&&!['--enable-requested-edits','--replace-account-confirmed'].includes(v)))throw Error('USAGE: --account-email your-address [--enable-requested-edits] [--replace-account-confirmed]');
if(process.platform!=='win32')throw Error('WINDOWS_REQUIRED');
const personalEmail=normalizeAccount(args[1]);
const accountFile=join(root,'.private','account.json');
if(existsSync(accountFile)&&!args.includes('--replace-account-confirmed'))throw Error('ACCOUNT_ALREADY_CONFIGURED');
mkdirSync(join(root,'.private'),{recursive:true});
writeFileSync(accountFile,JSON.stringify({personalEmail})+'\n',{mode:0o600});
const helper=join(root,'connection','request-store.exe');
if(!existsSync(helper))throw Error('RUN_BUILD_WINDOWS_FIRST');
if(existsSync(join(root,'.private','action-control')))execFileSync(helper,['--check'],{stdio:'inherit',windowsHide:true});
else execFileSync(helper,['--initialize-approved-capability-store'],{stdio:'inherit',windowsHide:true});
const enabled=args.includes('--enable-requested-edits');
writeFileSync(join(root,'.private','action-control','action-policy.json'),JSON.stringify({mode:enabled?'assistant-requested-actions':'restricted',personalEmail,consentAuthority:'trusted-assistant-and-client',destructiveConfirmation:'fresh-preview-and-user-confirmation',enabledOperations:enabled?OPERATIONS:[]},null,2)+'\n',{mode:0o600});
console.log(enabled?'CONFIGURED_REQUESTED_EDIT_CAPABILITIES_REQUIRES_SEPARATE_GOOGLE_FULL_GRANT':'CONFIGURED_READ_ONLY_DEFAULT_NO_GOOGLE_GRANT_CREATED');
